import { createFileRoute } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { Ban, Clock3, KeyRound, ShieldCheck, Sparkles, TimerOff } from "lucide-react";
import { AdminShell } from "@/components/admin-shell";
import { LicenseFormDialog } from "@/components/license-form-dialog";
import { workspaceQuery } from "@/components/workspace-state";
import { effectiveStatus, type LicenseRow } from "@/lib/license-ui";

export const Route = createFileRoute("/_authenticated/dashboard")({ loader: ({ context }) => context.queryClient.ensureQueryData(workspaceQuery), head: () => ({ meta: [{ title: "Dashboard — License Control" }, { name: "description", content: "License totals and current activation status." }, { property: "og:title", content: "Dashboard — License Control" }, { property: "og:description", content: "License totals and current activation status." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Dashboard });
function Dashboard() { const { data } = useSuspenseQuery(workspaceQuery); const licenses = data.licenses as LicenseRow[]; const counts = { total: licenses.length, active: licenses.filter(l=>effectiveStatus(l)==="active").length, expired: licenses.filter(l=>effectiveStatus(l)==="expired").length, revoked: licenses.filter(l=>effectiveStatus(l)==="revoked").length, trial: licenses.filter(l=>l.license_type==="trial").length, unactivated: licenses.filter(l=>effectiveStatus(l)==="unactivated").length }; const cards = [["Total licenses",counts.total,KeyRound],["Active",counts.active,ShieldCheck],["Expired",counts.expired,TimerOff],["Revoked",counts.revoked,Ban],["Trial",counts.trial,Sparkles],["Unactivated",counts.unactivated,Clock3]] as const; return <AdminShell title="Overview" description={`Welcome back${data.profile?.display_name ? `, ${data.profile.display_name}` : ""}. Here is the current license position.`} action={<LicenseFormDialog />}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{cards.map(([label,value,Icon])=><div key={label} className="border bg-card p-4"><div className="mb-5 flex items-center justify-between text-muted-foreground"><span className="text-xs font-medium">{label}</span><Icon className="size-4" /></div><p className="text-3xl font-semibold">{value}</p></div>)}</div><div className="mt-7 grid gap-5 lg:grid-cols-[1.4fr_0.6fr]"><section className="border bg-card p-5"><h2 className="font-semibold">Recent licenses</h2><div className="mt-4 divide-y">{licenses.slice(0,6).map(l=><div key={l.id} className="flex items-center justify-between gap-4 py-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{l.customers.name}</p><p className="mt-0.5 truncate font-mono text-xs text-muted-foreground">{l.key_preview}</p></div><span className="text-xs capitalize text-muted-foreground">{effectiveStatus(l)}</span></div>)}{!licenses.length&&<p className="py-10 text-center text-sm text-muted-foreground">No licenses issued yet.</p>}</div></section><section className="border bg-card p-5"><h2 className="font-semibold">System</h2><div className="mt-4 space-y-4 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Product</span><span>Browser Extension Core</span></div><div className="flex justify-between"><span className="text-muted-foreground">Validation API</span><span className="text-success">Ready</span></div><div className="flex justify-between"><span className="text-muted-foreground">Device limit</span><span>1 per license</span></div></div></section></div></AdminShell>; }