import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { useQueryClient } from "@tanstack/react-query";
import { Check, Copy, LoaderCircle, Plus } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { createLicense } from "@/lib/licenses.functions";

export function LicenseFormDialog() {
  const create = useServerFn(createLicense); const client = useQueryClient();
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [key, setKey] = useState("");
  const [type, setType] = useState<"trial" | "paid" | "custom">("paid");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const values = new FormData(event.currentTarget); try { const result = await create({ data: { customerName: String(values.get("name") ?? ""), phone: String(values.get("phone") ?? ""), email: String(values.get("email") ?? ""), handle: String(values.get("handle") ?? ""), customerNotes: String(values.get("customerNotes") ?? ""), licenseNotes: String(values.get("licenseNotes") ?? ""), licenseType: type, duration: { days: Number(values.get("days")), hours: Number(values.get("hours")), minutes: Number(values.get("minutes")), seconds: Number(values.get("seconds")) }, amountPaid: Number(values.get("amount") ?? 0), paymentReference: String(values.get("paymentReference") ?? "") } }); setKey(result.licenseKey); await client.invalidateQueries({ queryKey: ["admin-workspace"] }); toast.success("License created"); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to create license"); } finally { setBusy(false); } }
  function close(next: boolean) { setOpen(next); if (!next) setKey(""); }
  return <Dialog open={open} onOpenChange={close}><DialogTrigger asChild><Button><Plus />New license</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{key ? "License created" : "Create license"}</DialogTitle><DialogDescription>{key ? "Copy this key and send it securely to the customer." : "The license term begins on first activation."}</DialogDescription></DialogHeader>{key ? <div className="space-y-5"><div className="rounded-md border bg-muted p-4 font-mono text-sm break-all">{key}</div><Button className="w-full" onClick={async () => { await navigator.clipboard.writeText(key); toast.success("License key copied"); }}><Copy />Copy license key</Button></div> : <form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Customer name" name="name" required /><Field label="Email" name="email" type="email" /><Field label="WhatsApp / phone" name="phone" /><Field label="Username / handle" name="handle" /></div><div className="space-y-2"><Label>License type</Label><Select value={type} onValueChange={(value) => setType(value as typeof type)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="trial">Trial</SelectItem><SelectItem value="paid">Paid</SelectItem><SelectItem value="custom">Custom</SelectItem></SelectContent></Select></div><div><Label>Duration</Label><div className="mt-2 grid grid-cols-2 gap-3 sm:grid-cols-4"><Field label="Days" name="days" type="number" defaultValue="30" min="0" /><Field label="Hours" name="hours" type="number" defaultValue="0" min="0" max="23" /><Field label="Minutes" name="minutes" type="number" defaultValue="0" min="0" max="59" /><Field label="Seconds" name="seconds" type="number" defaultValue="0" min="0" max="59" /></div></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Amount paid" name="amount" type="number" defaultValue="0" min="0" step="0.01" /><Field label="Payment reference" name="paymentReference" /></div><div className="space-y-1.5"><Label htmlFor="customerNotes">Customer notes</Label><Textarea id="customerNotes" name="customerNotes" /></div><div className="space-y-1.5"><Label htmlFor="licenseNotes">License notes</Label><Textarea id="licenseNotes" name="licenseNotes" /></div><Button className="w-full" disabled={busy}>{busy ? <LoaderCircle className="animate-spin" /> : <Check />}Generate secure key</Button></form>}</DialogContent></Dialog>;
}
function Field({ label, name, ...props }: { label: string; name: string } & React.ComponentProps<typeof Input>) { return <div className="space-y-1.5"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} {...props} /></div>; }